/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TempSensorJNI */

#ifndef _Included_TempSensorJNI
#define _Included_TempSensorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TempSensorJNI
 * Method:    getTemp
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_TempSensorJNI_getTemp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
